name: Build CV

on:
  push:
    branches:
      - main
  workflow_call: # to make the workflow triggerable from other workflows (release.yml)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: RenderCV
        run: |
          cd src
          cv_file=$(find .  -maxdepth 1 -type f -name "*_CV.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV file found!"
            exit 1
          fi
          cd ..
          uv run rendercv render src/$cv_file --pdf-path ${cv_file%.yaml}.pdf

      - name: Upload output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          base: HEAD
          filters: |
            cv:
              - '*_CV.typ'

      - name: Push the changes
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Render the latest CV"
          git push
