name: Build CV

on:
  push:
    branches:
      - main
  workflow_call: # to make the workflow triggerable from other workflows (release.yml)

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: RenderCV
        run: |
          cd src
          cv_file=$(find .  -maxdepth 1 -type f -name "*_CV.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV file found!"
            exit 1
          fi
          cd ..
          uv run rendercv render src/$cv_file

      - name: List generated files (debug)
        run: |
          echo "Files in current directory:"
          ls -la
          echo "Looking for rendercv_output:"
          ls -la rendercv_output/ || echo "rendercv_output directory not found"
          echo "Looking for other output directories:"
          find . -name "*.pdf" -type f

      - name: Upload output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
