name: Create Release

on:
  workflow_run:
    workflows: ["Build CV"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Download CV artifacts
        uses: actions/download-artifact@v4
        with:
          name: cv-output
          path: rendercv_output/
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Generate release tag
        id: tag
        run: echo "tag=v$(date +'%Y.%m.%d-%H%M')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "Automated CV release generated on $(date +'%Y-%m-%d %H:%M')"
          files: rendercv_output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
