name: Create Release

on:
  push:
    tags:
      - "*" # Any tag pushed to the repository

permissions:
  contents: write

jobs:
  call_build_workflow:
    name: RenderCV
    uses: ./.github/workflows/build.yml
  release:
    needs: call_build_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
